# Generated by Django 4.2.7 on 2025-09-06 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_docs'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='docs_save_only_items',
            field=models.BooleanField(default=True),
        ),
    ]
