# Generated by Django 4.2.7 on 2025-09-06 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_docs_save_only_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='docs_save_only_items',
            field=models.BooleanField(default=True, help_text="Only save '/items' paths from the docs"),
        ),
    ]
