# Generated by Django 4.2.7 on 2025-09-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_project_docs_save_only_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='endpoint_base',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
