# Generated by Django 4.2.7 on 2025-09-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_project_endpoint_base'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='docs_save_only_items',
        ),
        migrations.AddField(
            model_name='project',
            name='docs_save_only_items_assets',
            field=models.BooleanField(default=True, help_text="Only save '/items' and '/assets' paths from the docs"),
        ),
    ]
