# Generated by Django 4.2.7 on 2025-09-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_project_docs_save_only_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
