# Generated by Django 4.2.7 on 2025-09-10 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_endpoint_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endpoint',
            name='name',
        ),
    ]
