# Generated by Django 4.2.7 on 2025-09-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_endpoint_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='logs',
            field=models.TextField(default=''),
        ),
    ]
