# Generated by Django 4.2.7 on 2025-09-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_endpoint_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='api_id',
            field=models.IntegerField(default=0),
        ),
    ]
