# Generated by Django 4.2.7 on 2025-09-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_endpoint_api_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='api_id',
            field=models.IntegerField(default=1, help_text='The id to replace in the url api call (if exists)'),
        ),
    ]
