# Generated by Django 4.2.7 on 2025-09-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_endpoint_api_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endpoint',
            name='logs',
        ),
        migrations.AddField(
            model_name='project',
            name='logs',
            field=models.TextField(default=''),
        ),
    ]
