# Generated by Django 4.2.7 on 2025-09-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_endpoint_logs_project_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='methods',
            field=models.ManyToManyField(blank=True, to='core.method'),
        ),
    ]
