# Generated by Django 4.2.7 on 2025-09-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_endpoint_methods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
