# Generated by Django 4.2.7 on 2025-09-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_endpoint_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='api_id',
            field=models.CharField(default='1', help_text='The id to replace in the url api call (if exists)', max_length=100),
        ),
    ]
